### ISSUE TITLE
Set up PyMongo ETL pipeline

### ISSUE THREAD

**Issue by Sho-Shoo** [Sho-Shoo/FCE-Bot#4]
Need to pipeline FCE data from a CSV (or directly from website if we have web-scrapping expertise) using PyMongo client. This will be in the form of a series of scripts, which will be executed by the end of each semester when FCE data is updated.

**Comment by abdurafeyf** [comment]
Can I get this assigned to me?

**Comment by Sho-Shoo** [comment]
Hi @abdurafeyf! Unfortunately, I am already working on this. I am currently laying down the framework for this project, so probably not accepting much open-source contribution. I will open more issues for open-source contributions later, please be looking out!
